image: node:20

pages:
  stage: deploy
  script:
    - cd apps/web
    - npm ci
    - NEXT_PUBLIC_BASE_PATH="/${CI_PROJECT_NAME}" npm run build
    - npx next export -o out
    - mv out ../public
    - cd ..
  artifacts:
    paths:
      - public
  only:
    - main


