# GitLab CI/CD Pipeline for MIT Class 863.25
# Deploys the htmaa2 portfolio to GitLab Pages

stages:
  - build
  - deploy

variables:
  NODE_VERSION: "20"

# Build stage
build:
  stage: build
  image: node:${NODE_VERSION}
  cache:
    paths:
      - node_modules/
      - apps/web/node_modules/
      - apps/desktop/node_modules/
  script:
    # Install dependencies
    - npm ci
    
    # Build web app for GitLab Pages
    - cd apps/web
    - BUILD_FOR_GITLAB=true npm run build
    
    # Build desktop app
    - cd ../desktop
    - npm run build
    
    # Export web app and create SPA fallback
    - cd ../web
    - cp out/index.html out/404.html
    - touch out/.nojekyll
    
    # Copy desktop app to web app's out directory
    - mkdir -p out/desktop
    - cp -r ../desktop/out/* out/desktop/
    
    # Create artifacts for deployment
    - mkdir -p public
    - cp -r out/* public/
  artifacts:
    paths:
      - public/
    expire_in: 1 hour

# Deploy to GitLab Pages
pages:
  stage: deploy
  dependencies:
    - build
  script:
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main
