name: Deploy htmaa2 to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      # Build web app with GitHub Pages configuration
      - name: Build web app
        run: |
          cd apps/web
          BUILD_FOR_GITHUB=true npm run build

      # Build desktop app with GitHub Pages configuration
      - name: Build desktop app
        run: |
          cd apps/desktop
          npm run build

      # Export the web app and create SPA fallback
      - name: Export web
        working-directory: apps/web
        run: |
          cp out/index.html out/404.html
          touch out/.nojekyll

      # Copy desktop app to web app's out directory
      - name: Copy desktop app
        run: |
          mkdir -p apps/web/out/desktop
          cp -r apps/desktop/out/* apps/web/out/desktop/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4