name: Build and push to CBA GitLab

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install and build static site
        env:
          DEPLOY_TARGET: "gitlab"
          NEXT_PUBLIC_TARGET_URL: "https://gitlab.cba.mit.edu/classes/863.25/people/HayleyBloch/"
          NEXT_PUBLIC_BASE_PATH: "/htmaa2"
        run: |
          npm ci
          # Build web and desktop and assemble a single static output at repo-root out/
          npm run build:static
          test -d out

      - name: Clone GitLab destination (shallow)
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: |
          # If your GitLab instance requires the :846 HTTPS port, include it here (this repo's remote uses it).
          git clone --depth=1 --branch main https://oauth2:${GITLAB_TOKEN}@gitlab.cba.mit.edu:846/classes/863.25/people/HayleyBloch.git gitlab-repo || \
            (git clone --depth=1 https://oauth2:${GITLAB_TOKEN}@gitlab.cba.mit.edu/classes/863.25/people/HayleyBloch.git gitlab-repo && cd gitlab-repo && git checkout -b main)

      - name: Prepare repo, sync built site and push
        env:
          COMMITTER_NAME: "Hayley Bloch"
          COMMITTER_EMAIL: "hayleybl@mit.edu"
        run: |
          cd gitlab-repo
          git fetch origin main --depth=1 || true
          git pull --ff-only origin main || true

          # Sync build output into the checked-out repo
          cd ..
          rsync -av --delete out/ gitlab-repo/

          cd gitlab-repo
          git config user.name "${COMMITTER_NAME}"
          git config user.email "${COMMITTER_EMAIL}"

          git add -A
          git commit -m "${{ github.event.head_commit.message || 'Site update from GitHub Actions' }}" || echo "No changes to commit"
          git push origin main
